# Configuração de Deploy e Monitoramento

# Configuração de Deploy
deployment:
  # Plataforma de Deploy
  platform: "vertex_ai"  # vertex_ai, cloud_run, kubernetes, docker
  
  # Configuração do Vertex AI Agent Engine
  vertex_ai:
    project_id: "${GOOGLE_CLOUD_PROJECT}"
    location: "${VERTEX_AI_LOCATION}"
    agent_name: "paradigm-architect-agent"
    
    # Configuração de Recursos
    resources:
      cpu: "2"
      memory: "4Gi"
      gpu: false
      
    # Configuração de Scaling
    scaling:
      min_replicas: 1
      max_replicas: 10
      target_cpu_utilization: 70
      target_memory_utilization: 80
      
    # Configuração de Rede
    network:
      vpc: "default"
      subnet: "default"
      ingress: "internal"  # internal, external

# Configuração de Monitoramento
monitoring:
  # Métricas Principais
  metrics:
    # Métricas de Performance
    performance:
      - name: "response_latency"
        description: "Latência de resposta do agente"
        unit: "milliseconds"
        target: 5000
        
      - name: "throughput"
        description: "Requisições processadas por minuto"
        unit: "requests/minute"
        target: 100
        
      - name: "error_rate"
        description: "Taxa de erro nas requisições"
        unit: "percentage"
        target: 1
        
    # Métricas de Negócio
    business:
      - name: "conversion_rate"
        description: "Taxa de conversão influenciada pelo agente"
        unit: "percentage"
        target: 15
        
      - name: "framework_effectiveness"
        description: "Efetividade dos frameworks gerados"
        unit: "score"
        target: 8.5
        
      - name: "user_satisfaction"
        description: "Satisfação dos usuários com as respostas"
        unit: "score"
        target: 9.0

# Configuração de Logging
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Estrutura de Logs
  structure:
    format: "json"
    include_timestamp: true
    include_request_id: true
    include_user_id: true
    include_session_id: true
    
  # Retenção de Logs
  retention:
    default: "90_days"
    error_logs: "1_year"
    performance_logs: "30_days"
    debug_logs: "7_days"

# Configuração de Segurança
security:
  # Autenticação
  authentication:
    required: true
    methods: ["api_key", "oauth2", "service_account"]
    
  # Criptografia
  encryption:
    in_transit: true
    at_rest: true
    key_management: "google_kms"

